name-template: 'Release v{{version}}'
tag-template: 'v{{version}}'
categories:
  - title: '🚀 New Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
change-template: '- {{change}}'
no-changes-template: 'No changes in this release.'
version-resolver:
  custom:
    value: ${{ env.VERSION }}  # Используется переменная из workflow
draft: false