name-template: 'Release v${{ env.VERSION }}'
tag-template: 'v${{ env.VERSION }}'
version-resolver:
  custom:
    value: ${{ env.VERSION }}
categories:
  - title: '🚀 New Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
change-template: '- {{text}} (#{{number}} by @{{author}})'
no-changes-template: 'No changes in this release.'
template: |
  ## What's Changed

  $CHANGES

  **Contributors**:
  $CONTRIBUTORS
draft: false