name-template: 'vRESOLVED_VERSION'
tag-template: 'vRESOLVED_VERSION'

categories:
  - title: '💥 Breaking Changes'
    labels:
      - breaking-change
  - title: '🚀 New Features'
    labels:
      - feature
  - title: '🐛 Bug Fixes'
    labels:
      - bug
      - fix
      - bugfix
  - title: '🛠️ Technical Debt'
    labels:
      - refactor

change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
no-changes-template: 'No significant changes'

template: |
  ## 🚀 Release v$RESOLVED_VERSION

  ### What's Changed
  $CHANGES

  **Contributors:** $CONTRIBUTORS

version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
  patch:
    labels:
      - patch
  default: patch
