name-template: 'Release v${{ env.VERSION }}'
tag-template: 'v${{ env.VERSION }}'
categories:
  - title: '🚀 New Features'
    labels:
      - feature
  - title: '🐛 Bug Fixes'
    labels:
      - bugfix
  - title: '🛠️ Technical Debt'
    labels:
      - refactor
change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
no-changes-template: 'No significant changes'
template: |
  ## 🚀 Release v${{ env.VERSION }}

  ### What's Changed
  $CHANGES

  **Contributors:** $CONTRIBUTORS
