name: 'Commit and Push'
description: 'Check a specified tag'
inputs:
  author_name:
    description: 'User'
    required: false
  author_email:
    description: 'Email'
    required: false
  commit_message:
    description: 'Commit Message'
    required: false

runs:
  using: 'node16'
  main: 'index.js'
