name: 'Commit and Push'
description: 'Check a specified tag'
inputs:
  author_name:
    description: 'Author Name'
    required: false
  author_email:
    description: 'Author Email'
    required: false
  commit_message:
    description: 'Commit Message'
    required: false

runs:
  using: 'node16'
  main: 'dist/index.js'
