name: 'Xml Replace Action'
description: 'Check a specified tag'
inputs:
  name:
    description: ''
    required: true
  greeting:
    description: ''
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'