name: Custom Action

on:
  workflow_dispatch:
    inputs:
      version:
        required: false
        type: string
jobs:
  my-action:
    runs-on: ubuntu-latest
    steps:
      - name: Run my Action
        uses: ./actions/xml-replace@main
        with:
          name: 'Fucker'
          greeting: 'my boy'