name: Custom Action

on:
  workflow_dispatch:

jobs:
  my-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run my Action
        uses: ./actions/xml-replace
        with:
          name: 'Fucker'
          greeting: 'my boy'