name: Custom Action

on:
  workflow_dispatch:
    inputs:
      path:
          description: 'Path to the file'
          default: 'pom.xml'
          required: true
      newValue:
          description: 'Replacement string'
          default: '1.0.0'
          required: true
      commit:
          description: 'Commit changes'
          type: boolean
          default: false
          required: false


jobs:
  my-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run my Action
        uses: ./actions/xml-replace
        with:
          path: ${{ inputs.path }}
          newValue: ${{ inputs.newValue }}
          commit: ${{ inputs.commit }}