name: Custom Action

on:
  workflow_dispatch:
    inputs:
      newValue:
          description: 'Replacement string'
          default: '1.0.0'
          required: true

jobs:
  my-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run my Action
        uses: ./actions/pom-updater
        with:
          newValue: ${{ inputs.newValue }}
          filePath: 'pom.xml'
      - name: Commit and Push
        uses: ./actions/commit-and-push
