name: Custom Action

on:
  workflow_dispatch:
    inputs:
      path:
          description: 'Path to the file'
          default: 'pom.xml'
          required: true
      replacement:
          description: 'Replacement string'
          default: '1.0.0'
          required: true


jobs:
  my-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run my Action
        uses: ./actions/xml-replace
        with:
          path: ${{ inputs.path }}
          replacement: ${{ inputs.replacement }}