name: Publish on release tag

on:
  release:
    types:
      - released

jobs:
  get_release_version:
    runs-on: ubuntu-latest
    outputs:
      release_version: ${{ steps.get_release_version.outputs.release_version }}
    steps:
      - name: Get release version
        id: get_release_version
        run: |
          TAG_NAME=${GITHUB_EVENT_RELEASE_TAG_NAME}
          RELEASE_VERSION=${TAG_NAME#v}
          echo "release_version=$RELEASE_VERSION" >> $GITHUB_ENV
        env:
          GITHUB_EVENT_RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}
          
  pom:
    needs: get_release_version
    uses: nookyo/workflow-hub/.github/workflows/update-pom-release.yml@main
    with:
      file: pom.xml
      revision: ${{ needs.get_release_version.outputs.release_version }}


#   maven:
#     uses: Netcracker/qubership-workflow-hub/.github/workflows/maven-publish.yml@main
#     needs: pom
#     with:
#       maven_command: "--batch-mode deploy"
#       java_version: '21'
#       revision: ${{ steps.get_release_version.outputs.release_version }}
#     secrets:
#       maven_username: ${{ secrets.MAVEN_USER }}
#       maven_password: ${{ secrets.MAVEN_PASSWORD }}
#       maven_gpg_passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
#       maven_gpg_private_key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}