name: Release v2

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        default: '2025.1-1.0.0'
        type: string
        description: 'Custom release version'
      publish:
        required: true
        type: boolean
        default: false
        description: 'Enable publish release?'

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check Tag Exists
        uses: ./my-tag-checker-action
        id: check_tag
        with:
          tag_name: "v1.0.0"
  
      - name: Debug Output
        run: echo "Tag exists: ${{ steps.check_tag.outputs.exists }}"




    uses:  nookyo/workflow-hub/.github/workflows/release-drafter.yml@main   
    with:
      version: ${{ github.event.inputs.version }}
      publish: ${{ github.event.inputs.publish }}

#   pom:
#     uses: Netcracker/qubership-workflow-hub/.github/workflows/update-pom-release.yml@main
#     needs: release
#     with:
#       file: pom.xml
#       revision: ${{ github.event.inputs.version }}
          

#   maven:
#     uses: Netcracker/qubership-workflow-hub/.github/workflows/maven-publish.yml@main
#     needs: pom
#     with:
#       maven_command: "--batch-mode deploy"
#       java_version: "21"
#       revision: ${{ github.event.inputs.version }}
#     secrets:
#       maven_username: ${{ secrets.MAVEN_USER }}
#       maven_password: ${{ secrets.MAVEN_PASSWORD }}
#       maven_gpg_passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE  }}
#       maven_gpg_private_key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY  }}
